### ISSUE TITLE
package.json refers to lib/index.js but file not in repository

### ISSUE THREAD

**Issue by MartinWillitts** [bokuweb/re-bulma#84] opened 2017-06-13 16:31 UTC
Hello, I am trying to make use of the bokuweb main branch rather than my fork. I notice the package.json has `"main": "lib/index.js",` and that the file does not exist in the repository. I'm not familiar with node modules. Should it be there and if not then how is it built if it's even needed? (I'm finding my code cannot find re-bulma in the 'import' call.)

**Comment by capaj** [comment] 2017-06-13 16:54
lib directory is not checked into git.

![image](https://user-images.githubusercontent.com/1305378/27094090-45c22918-5069-11e7-99a0-f0dc8a0578f4.png)

it's only uploaded onto npm. npm does indeed have `lib` and `index.js` inside it.
If you're using webpack it might just be that your webpack config is wrong. Setting up webpack can be pretty hard even for a seasoned JS dev. If you post your directory tree, your webpack config and the error you're getting I might be able to advise you.

SInce this is not a bug, I am closing this but feel free to post more details here or on stackoverflow.

**Closed by capaj** 2017-06-13 16:54 UTC
